dist: trusty
sudo: required

group: edge

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

script:
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker build -t goloschain/golos:"$TRAVIS_TAG" . ;
    else
      docker build -t goloschain/golos:latest . ;
    fi
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push goloschain/golos:latest;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
      GOOD_TAG="$TRAVIS_TAG" ;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      if [[ "$TRAVIS_TAG" =~ ^v[0-9]{1,3}\..* ]]; then
          GOOD_TAG=$(echo "$TRAVIS_TAG" | cut -c2-) ;
      fi
      docker tag goloschain/golos:"$TRAVIS_TAG" goloschain/golos:"$GOOD_TAG" ;
      docker push goloschain/golos:"$GOOD_TAG" ;
    fi

