sudo: required

language: cpp

services:
  - docker

addons:
  ssh_known_hosts: developers.golos.io

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

script:
#  - if [ -n "${TRAVIS_TAG}" ]; then
#      docker build -t goloschain/golos:"$TRAVIS_TAG" . ;
#    else
#      docker build -t goloschain/golos:latest . ;
#    fi
  - docker images

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] || [[ "$TRAVIS_BRANCH" =~ ^golos- ]]; then
      bash deploy/deploy.sh;
    fi
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#      docker push goloschain/golos:latest;
#    fi
#  - if [ -n "$TRAVIS_TAG" ]; then
#      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#      docker push goloschain/golos:"$TRAVIS_TAG";
#    fi

